[compiler.solc]
exclude_paths = [
    "venv",
    ".venv",
    "core/node_modules",
    "core/contracts/0.4.24",
    "core/contracts/common/test_helpers/SignatureUtilsConsumer_0_4_24.sol",
    "core/contracts/common/lib/SignatureUtils.sol",
    "core/contracts/common/lib/ECDSA.sol",
    "core/test",
    "core/script",
    "core/lib",
    "core/foundry/lib",
    "csm/node_modules",
    "csm/script",
    "csm/test",
    "easy-track/contracts/dependencies",
    "easy-track/node_modules",
    "tests",
    "core/contracts/0.6.12",
    "core/contracts/0.6.11",
    "core/contracts/0.8.4",
]

remappings = [
    "core:@openzeppelin/contracts/=core/node_modules/@openzeppelin/contracts/",
    "core:@openzeppelin/contracts-v4.4/=core/node_modules/@openzeppelin/contracts-v4.4/",
    "core:@openzeppelin/contracts-upgradeable/=core/node_modules/@openzeppelin/contracts-upgradeable/",
    "core:forge-std/=core/node_modules/forge-std/src/",
    "core:ds-test/=core/node_modules/ds-test/src/",
    "csm:@openzeppelin/contracts/=csm/node_modules/@openzeppelin/contracts/",
    "csm:@openzeppelin/contracts-v4.4/=csm/node_modules/@openzeppelin/contracts-v4.4/",
    "csm:@openzeppelin/contracts-upgradeable/=csm/node_modules/@openzeppelin/contracts-upgradeable/",
    "csm:forge-std/=csm/node_modules/forge-std/src/",
    "csm:ds-test/=csm/node_modules/ds-test/src/",
    "easy-track:OpenZeppelin/=easy-track/dependencies/OpenZeppelin/",
]

[subproject.core]
paths = ["core"]
evm_version = "istanbul"
target_version = "0.8.9"

[subproject.core.optimizer]
enabled = true
runs = 200

[subproject.csm]
paths = ["csm", "tests/helpers"]
evm_version = "cancun"

[subproject.csm.optimizer]
enabled = true
runs = 250

[subproject.csm.metadata]
bytecode_hash = "none"

[subproject."easy-track"]
paths = ["easy-track"]
evm_version = "istanbul"

[subproject."easy-track".optimizer]
enabled = true
runs = 200

[detectors]
exclude = []
ignore_paths = ["venv", ".venv", "test"]
exclude_paths = ["node_modules", "lib", "script"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
